(function () {
  window.ListeningDeskTopics = Object.freeze({
    "intervals": {name:'Intervals',title:'Major third vs. Minor third',subtitle:'See the notation, hear the distance, then compare both sounds.',intro:'A third spans three letter names. The major third contains four semitones; the minor third contains three.',examples:[
      {label:'Major third',notation:{type:'interval',notes:['c/4','e/4']},explanation:'Four semitones: C to E. Hear the open, settled quality.',parts:[['Lower note · C',[60]],['Upper note · E',[64]]]},
      {label:'Minor third',notation:{type:'interval',notes:['c/4','eb/4']},explanation:'Three semitones: C to E-flat. Hear the closer, darker quality.',parts:[['Lower note · C',[60]],['Upper note · E♭',[63]]]}
    ]},
    "cadences": {name:'Cadences',title:'Perfect cadence vs. Imperfect cadence',subtitle:'Hear whether a phrase feels finished.',intro:'Cadences shape musical endings. Compare a close-voiced V–I resolution with a cadence that ends on V and keeps the music moving.',examples:[
      {label:'Perfect cadence',notation:{type:'cadence',key:'C',chords:[['b/3','d/4','g/4'],['c/4','e/4','g/4']]},explanation:'B rises to C, D rises to E, and G remains as a common note.',parts:[['V · B–D–G',[59,62,67]],['I · C–E–G',[60,64,67]]]},
      {label:'Imperfect cadence',notation:{type:'cadence',key:'C',chords:[['c/4','e/4','g/4'],['b/3','d/4','g/4']]},explanation:'The phrase moves from I to V and pauses without feeling completely finished.',parts:[['I · C–E–G',[60,64,67]],['V · B–D–G',[59,62,67]]]}
    ]},
    "triads": {name:'Triads and chords',title:'Build, hear and invert triads',subtitle:'Connect chord spelling, bass position and sound.',intro:'A triad stacks two thirds above a root. Compare major and minor triads, then follow I, ii, IV and V through root position, first inversion and second inversion.',examples:[
      {label:'C major triad',notation:{type:'triad',notes:['c/4','e/4','g/4']},explanation:'Root position places C in the bass. The major third gives the chord its major quality.',parts:[['Hear root · C',[60]],['Hear third and fifth',[64,67]]]},
      {label:'C minor triad',notation:{type:'triad',notes:['c/4','eb/4','g/4']},explanation:'Lowering E to E-flat changes the chord from major to minor.',parts:[['Hear root · C',[60]],['Hear third and fifth',[63,67]]]},
      {label:'First inversion',notation:{type:'triad',notes:['e/4','g/4','c/5']},explanation:'The third, E, is now the lowest note. The chord is still C major.',parts:[['Hear bass · E',[64]],['Hear upper notes',[67,72]]]},
      {label:'Second inversion',notation:{type:'triad',notes:['g/3','c/4','e/4']},explanation:'The fifth, G, is the lowest note. Inversion is determined by the bass.',parts:[['Hear bass · G',[55]],['Hear upper notes',[60,64]]]}
    ]},
    "time-signatures": {name:'Time signatures and grouping',title:'Read and hear how metre works',subtitle:'Build the skill step by step before you practise.',intro:'Learn what both numbers mean, how simple and compound beats divide, and how irregular bars are grouped. Every step connects the written notation to the accents you hear.',examples:[
      {label:'Read both numbers',rule:'The upper number tells you how many beats or subdivisions fill the bar; the lower number tells you which note value is being counted.',notation:{type:'rhythm',meter:[3,2],events:[{keys:['e/5'],duration:'h',group:1,accent:true},{keys:['e/5'],duration:'h',group:2,accent:true},{keys:['e/5'],duration:'h',group:3,accent:true}]},explanation:'In 3/2, the 3 means there are three beats in each bar and the 2 means each beat is a minim. Count the displayed bar slowly as “one, two, three.”',parts:[['Hear the three minim beats',[76,76,76]],['Hear the bar again',[76,76,76]]],audioType:'rhythm',groups:[1,1,1]},
      {label:'Simple metre divides each beat into two',rule:'In simple metre, each main beat divides naturally into two equal parts. The upper number usually gives the number of main beats.',notation:{type:'rhythm',meter:[4,4],events:[{keys:['e/5'],duration:'q',group:1,accent:true},{keys:['e/5'],duration:'q',group:2,accent:true},{keys:['e/5'],duration:'q',group:3,accent:true},{keys:['e/5'],duration:'q',group:4,accent:true}]},explanation:'This 4/4 bar contains four crotchet beats. Each crotchet can divide into two quavers, so count “one-and, two-and, three-and, four-and.”',parts:[['Hear four crotchet beats',[76,76,76,76]],['Hear the bar again',[76,76,76,76]]],audioType:'rhythm',groups:[1,1,1,1]},
      {label:'Compound metre divides each beat into three',rule:'In compound metre, each main beat divides into three equal parts. The written quavers are subdivisions of a dotted-note beat.',notation:{type:'rhythm',meter:[6,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2},{keys:['c/5'],duration:'8',group:2}]},explanation:'Six quavers in 6/8 form two dotted-crotchet beats, grouped 3+3. Count two main beats while feeling three quaver pulses inside each beat.',parts:[['Hear the 3+3 grouping',[76,72,72,76,72,72]],['Hear the bar again',[76,72,72,76,72,72]]],audioType:'rhythm',groups:[3,3]},
      {label:'Compare simple and compound metre',rule:'Do not decide from the total number of written notes alone. Find the main accents, then ask whether each beat divides into two or three.',notation:{type:'rhythm',meter:[3,4],events:[{keys:['e/5'],duration:'q',group:1,accent:true},{keys:['c/5'],duration:'q',group:2,accent:true},{keys:['c/5'],duration:'q',group:3,accent:true}]},explanation:'This 3/4 bar has three crotchet beats, so it is simple triple metre. By contrast, 6/8 has two dotted-crotchet beats even though both metres can contain six quavers.',parts:[['Hear three beats in 3/4',[76,72,72]],['Hear the simple triple pulse',[76,72,72]]],audioType:'rhythm',groups:[1,1,1]},
      {label:'Group an irregular 5/4 bar',rule:'Irregular metres combine unequal beat groups. Mark the start of each group first, because those positions receive the stronger accents.',notation:{type:'rhythm',meter:[5,4],events:[{keys:['e/5'],duration:'q',group:1,accent:true},{keys:['c/5'],duration:'q',group:1},{keys:['e/5'],duration:'q',group:2,accent:true},{keys:['c/5'],duration:'q',group:2},{keys:['c/5'],duration:'q',group:2}]},explanation:'Five crotchets can be felt as 2+3: two beats followed by three. The accents begin on beats 1 and 3, so say “ONE-two, ONE-two-three.”',parts:[['Hear 5/4 as 2+3',[76,72,76,72,72]],['Hear the accents again',[76,72,76,72,72]]],audioType:'rhythm',groups:[2,3]},
      {label:'Group an irregular 7/4 bar',rule:'A seven-beat bar is made manageable by dividing it into shorter groups. Read beaming, phrasing and accents to find the intended order.',notation:{type:'rhythm',meter:[7,4],events:[{keys:['e/5'],duration:'q',group:1,accent:true},{keys:['c/5'],duration:'q',group:1},{keys:['c/5'],duration:'q',group:1},{keys:['e/5'],duration:'q',group:2,accent:true},{keys:['c/5'],duration:'q',group:2},{keys:['e/5'],duration:'q',group:3,accent:true},{keys:['c/5'],duration:'q',group:3}]},explanation:'This 7/4 example is grouped 3+2+2. The stronger notes begin each group on beats 1, 4 and 6; another passage could arrange the groups differently.',parts:[['Hear 7/4 as 3+2+2',[76,72,72,76,72,76,72]],['Hear the accents again',[76,72,72,76,72,76,72]]],audioType:'rhythm',groups:[3,2,2]},
      {label:'The same 5/8 can feel different',rule:'The time signature gives the total length of the bar, but the grouping tells you where the internal accents fall: 2+3 and 3+2 are different.',notation:{type:'rhythm',meter:[5,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2},{keys:['c/5'],duration:'8',group:2}]},explanation:'This version is 2+3, so its second accent arrives on quaver 3. In a 3+2 version, the second accent moves to quaver 4 even though the metre remains 5/8.',parts:[['Hear 5/8 as 2+3',[76,72,76,72,72]],['Hear the shown grouping again',[76,72,76,72,72]]],audioType:'rhythm',groups:[2,3],variants:[
        {id:'2+3',label:'Irregular 5/8 · 2+3',notation:{type:'rhythm',meter:[5,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2},{keys:['c/5'],duration:'8',group:2}]},explanation:'Five quavers are grouped 2+3, with an accent at each group start.',parts:[['Hear 2+3',[76,72,76,72,72]],['Hear complete pattern',[76,72,76,72,72]]],groups:[2,3]},
        {id:'3+2',label:'Irregular 5/8 · 3+2',notation:{type:'rhythm',meter:[5,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2}]},explanation:'Five quavers are grouped 3+2, moving the second accent to the fourth quaver.',parts:[['Hear 3+2',[76,72,72,76,72]],['Hear complete pattern',[76,72,72,76,72]]],groups:[3,2]}
      ]},
      {label:'Use a reliable reading method',rule:'First identify the counted note value, then locate the main beats, divide or group them, and finally confirm the pattern by listening for accents.',notation:{type:'rhythm',meter:[7,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2},{keys:['e/5'],duration:'8',group:3,accent:true},{keys:['c/5'],duration:'8',group:3},{keys:['c/5'],duration:'8',group:3}]},explanation:'For this 7/8 bar: count seven quavers, see the 2+2+3 grouping, and check for accents on quavers 1, 3 and 5. Use those same four steps in practice.',parts:[['Hear the 2+2+3 reading',[76,72,76,72,76,72,72]],['Hear and count once more',[76,72,76,72,76,72,72]]],audioType:'rhythm',groups:[2,2,3],practiceCta:true,variants:[
        {id:'2+2+3',label:'Irregular 7/8 · 2+2+3',notation:{type:'rhythm',meter:[7,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2},{keys:['e/5'],duration:'8',group:3,accent:true},{keys:['c/5'],duration:'8',group:3},{keys:['c/5'],duration:'8',group:3}]},explanation:'Seven quavers are grouped 2+2+3, with an accent at each group start.',parts:[['Hear 2+2+3',[76,72,76,72,76,72,72]],['Hear complete pattern',[76,72,76,72,76,72,72]]],groups:[2,2,3]},
        {id:'2+3+2',label:'Irregular 7/8 · 2+3+2',notation:{type:'rhythm',meter:[7,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2},{keys:['c/5'],duration:'8',group:2},{keys:['e/5'],duration:'8',group:3,accent:true},{keys:['c/5'],duration:'8',group:3}]},explanation:'Seven quavers are grouped 2+3+2, placing the longer group in the middle.',parts:[['Hear 2+3+2',[76,72,76,72,72,76,72]],['Hear complete pattern',[76,72,76,72,72,76,72]]],groups:[2,3,2]},
        {id:'3+2+2',label:'Irregular 7/8 · 3+2+2',notation:{type:'rhythm',meter:[7,8],events:[{keys:['e/5'],duration:'8',group:1,accent:true},{keys:['c/5'],duration:'8',group:1},{keys:['c/5'],duration:'8',group:1},{keys:['e/5'],duration:'8',group:2,accent:true},{keys:['c/5'],duration:'8',group:2},{keys:['e/5'],duration:'8',group:3,accent:true},{keys:['c/5'],duration:'8',group:3}]},explanation:'Seven quavers are grouped 3+2+2, placing the longer group first.',parts:[['Hear 3+2+2',[76,72,72,76,72,76,72]],['Hear complete pattern',[76,72,72,76,72,76,72]]],groups:[3,2,2]}
      ]}
    ]},
    "scales": {name:'Major and minor scales',title:'Hear how scales are constructed',subtitle:'Follow each scale degree in notation and sound.',intro:'A major scale follows a fixed tone–semitone pattern. Harmonic minor raises degree 7; melodic minor raises degrees 6 and 7 ascending, while a chromatic scale moves entirely by semitone.',examples:[
      {label:'C major scale',notation:{type:'scale',notes:['c/4','d/4','e/4','f/4','g/4','a/4','b/4','c/5'],descendingNotes:['c/5','b/4','a/4','g/4','f/4','e/4','d/4','c/4']},explanation:'The major scale follows 2–2–1–2–2–2–1 semitones in both directions.',parts:[['Hear ascent',[60,62,64,65,67,69,71,72]],['Hear descent',[72,71,69,67,65,64,62,60]]],audioType:'sequence'},
      {label:'A harmonic minor',notation:{type:'scale',notes:['a/3','b/3','c/4','d/4','e/4','f/4','g#/4','a/4'],descendingNotes:['a/4','g#/4','f/4','e/4','d/4','c/4','b/3','a/3']},explanation:'The raised seventh, G-sharp, creates the characteristic augmented second in both directions.',parts:[['Hear ascent',[57,59,60,62,64,65,68,69]],['Hear descent',[69,68,65,64,62,60,59,57]]],audioType:'sequence'},
      {label:'A melodic minor',notation:{type:'scale',notes:['a/3','b/3','c/4','d/4','e/4','f#/4','g#/4','a/4'],descendingNotes:['a/4','g/4','f/4','e/4','d/4','c/4','b/3','a/3']},explanation:'Ascending melodic minor raises the sixth and seventh degrees; descending it returns to natural minor.',parts:[['Hear ascent',[57,59,60,62,64,66,68,69]],['Hear descent',[69,67,65,64,62,60,59,57]]],audioType:'sequence'},
      {label:'C chromatic scale',notation:{type:'scale',notes:['c/4','c#/4','d/4','d#/4','e/4','f/4','f#/4','g/4','g#/4','a/4','bb/4','b/4','c/5'],descendingNotes:['c/5','b/4','bb/4','a/4','ab/4','g/4','gb/4','f/4','e/4','eb/4','d/4','db/4','c/4']},explanation:'A chromatic scale rises with sharps and descends with conventional flat spellings.',parts:[['Hear ascent',[60,61,62,63,64,65,66,67,68,69,70,71,72]],['Hear descent',[72,71,70,69,68,67,66,65,64,63,62,61,60]]],audioType:'sequence'}
    ]},
    "scale-degrees": {name:'Scale degrees and technical names',title:'Name every scale degree',subtitle:'Follow the seven technical names in major and minor keys.',intro:'Degrees 1–6 retain their technical names in major and minor. Degree 7 is the leading note when it is one semitone below tonic, and the subtonic when it is a whole tone below tonic.',examples:[
      {label:'C major · leading note',notation:{type:'scale',notes:['c/4','d/4','e/4','f/4','g/4','a/4','b/4','c/5'],descendingNotes:['c/5','b/4','a/4','g/4','f/4','e/4','d/4','c/4'],ascendingDegreeLabels:['Tonic','Supertonic','Mediant','Subdominant','Dominant','Submediant','Leading note','Tonic'],descendingDegreeLabels:['Tonic','Leading note','Submediant','Dominant','Subdominant','Mediant','Supertonic','Tonic']},explanation:'Ascending and descending, B is the leading note because it lies one semitone below C.',parts:[['Hear ascent',[60,62,64,65,67,69,71,72]],['Hear descent',[72,71,69,67,65,64,62,60]]],audioType:'sequence'},
      {label:'A natural minor · subtonic',notation:{type:'scale',notes:['a/3','b/3','c/4','d/4','e/4','f/4','g/4','a/4'],descendingNotes:['a/4','g/4','f/4','e/4','d/4','c/4','b/3','a/3'],ascendingDegreeLabels:['Tonic','Supertonic','Mediant','Subdominant','Dominant','Submediant','Subtonic','Tonic'],descendingDegreeLabels:['Tonic','Subtonic','Submediant','Dominant','Subdominant','Mediant','Supertonic','Tonic']},explanation:'In both directions, G is the subtonic because it lies a whole tone below A.',parts:[['Hear ascent',[57,59,60,62,64,65,67,69]],['Hear descent',[69,67,65,64,62,60,59,57]]],audioType:'sequence'},
      {label:'A melodic minor · changing degree 7',notation:{type:'scale',notes:['a/3','b/3','c/4','d/4','e/4','f#/4','g#/4','a/4'],descendingNotes:['a/4','g/4','f/4','e/4','d/4','c/4','b/3','a/3'],ascendingDegreeLabels:['Tonic','Supertonic','Mediant','Subdominant','Dominant','Submediant','Leading note','Tonic'],descendingDegreeLabels:['Tonic','Subtonic','Submediant','Dominant','Subdominant','Mediant','Supertonic','Tonic']},explanation:'Ascending melodic minor uses G-sharp as the leading note; descending it uses G-natural as the subtonic.',parts:[['Hear ascent',[57,59,60,62,64,66,68,69]],['Hear descent',[69,67,65,64,62,60,59,57]]],audioType:'sequence'},
    ]},
    "key-signatures": {name:'Key signatures and key relationships',title:'Same signature. Different home note.',subtitle:'Read the shared signature, then hear why relative major and minor keys feel different.',intro:'Relative major and minor keys use the same key signature and the same pitch collection. Their tonal centre changes: the major scale settles on its major tonic, while the minor scale settles on its relative minor tonic.',examples:[
      {label:'C major and A minor',bridgeLabel:'Same key signature · different tonic',major:{name:'C major',tonic:'C',keySignature:'C',notes:['c/4','d/4','e/4','f/4','g/4','a/4','b/4','c/5'],midis:[60,62,64,65,67,69,71,72]},minor:{name:'A minor',tonic:'A',keySignature:'C',notes:['a/3','b/3','c/4','d/4','e/4','f/4','g/4','a/4'],midis:[57,59,60,62,64,65,67,69]}},
      {label:'G major and E minor',bridgeLabel:'Same key signature · different tonic',major:{name:'G major',tonic:'G',keySignature:'G',notes:['g/3','a/3','b/3','c/4','d/4','e/4','f#/4','g/4'],midis:[55,57,59,60,62,64,66,67]},minor:{name:'E minor',tonic:'E',keySignature:'G',notes:['e/4','f#/4','g/4','a/4','b/4','c/5','d/5','e/5'],midis:[64,66,67,69,71,72,74,76]}},
      {label:'E-flat major and C minor',bridgeLabel:'Same key signature · different tonic',major:{name:'E-flat major',tonic:'E♭',keySignature:'Eb',notes:['eb/4','f/4','g/4','ab/4','bb/4','c/5','d/5','eb/5'],midis:[63,65,67,68,70,72,74,75]},minor:{name:'C minor',tonic:'C',keySignature:'Eb',notes:['c/4','d/4','eb/4','f/4','g/4','ab/4','bb/4','c/5'],midis:[60,62,63,65,67,68,70,72]}}
    ],reference:[
      {signature:'No sharps or flats',major:'C major',minor:'A minor'},
      {signature:'1 sharp · F♯',major:'G major',minor:'E minor'},
      {signature:'2 sharps · F♯ C♯',major:'D major',minor:'B minor'},
      {signature:'3 sharps · F♯ C♯ G♯',major:'A major',minor:'F♯ minor'},
      {signature:'4 sharps · F♯ C♯ G♯ D♯',major:'E major',minor:'C♯ minor'},
      {signature:'5 sharps · F♯ C♯ G♯ D♯ A♯',major:'B major',minor:'G♯ minor'},
      {signature:'6 sharps · F♯ C♯ G♯ D♯ A♯ E♯',major:'F♯ major',minor:'D♯ minor'},
      {signature:'1 flat · B♭',major:'F major',minor:'D minor'},
      {signature:'2 flats · B♭ E♭',major:'B♭ major',minor:'G minor'},
      {signature:'3 flats · B♭ E♭ A♭',major:'E♭ major',minor:'C minor'},
      {signature:'4 flats · B♭ E♭ A♭ D♭',major:'A♭ major',minor:'F minor'},
      {signature:'5 flats · B♭ E♭ A♭ D♭ G♭',major:'D♭ major',minor:'B♭ minor'},
      {signature:'6 flats · B♭ E♭ A♭ D♭ G♭ C♭',major:'G♭ major',minor:'E♭ minor'}
    ]}
  });
})();
